Fix(Db) Kezan, Correct Chain of Missions.
FirelandsProject/firelands-cata pull request #43
Opened 2022-08-30 02:34 UTC by Asmadeuxx

### Changes proposed

-  Correct order of start-up missions  goblins
-  Creature Text esES, esMX.
- 

### Issues addressed

- Closes

### SOURCE:

- 
- 

### Tests performed

- 
- 

### How to Test the Changes:

1. 
2. 
3. 

### Known issues and TODO list

- [ ] 
- [ ] 

---

- Thank you for collaborating with the project.
- For an efficient working methodology.
- It is obvious to make long pull request, unless it is necessary.
- A short pull request would be easy to test and approve.

2022-08-30 05:01 UTC, pangolp commented
I am writing to you privately, because you need to correct some things.

2022-08-30 14:44 UTC, seobryn requested changes

2022-08-30 14:44 UTC, seobryn commented on data/sql/updates/pending_db_world/rev_1661826488559382300.sql
> +UPDATE `quest_template_addon` SET `PrevQuestID` = '0' WHERE  `ID` = '14138';
@Asmadeuxx  Please remove single quotes in every number

2022-08-30 14:44 UTC, seobryn commented on data/sql/updates/pending_db_world/rev_1661826488559382300.sql
> +ALTER TABLE `creature_text_locale`
What do you want to do with this sentence? O_o.

Please review that.

2022-08-30 14:44 UTC, seobryn commented on data/sql/updates/pending_db_world/rev_1661826488559382300.sql
> +INSERT INTO `creature_text_locale` ( `CreatureID`,`GroupID`,`ID`,`Locale`,`Text`) VALUES
I'm not sure if this change has to be located on `broadcast_text_locale`

2022-08-31 16:25 UTC, pangolp approved these changes
Thanks

2022-08-31 16:25 UTC, pangolp commented on data/sql/updates/pending_db_world/rev_1661826488559382300.sql
> +DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceEntry` IN (14069, 14075,25473,28349,14071,24567,24488,24502,24503,24520,14070,26712,14113,14153,14115,14116,14120,14121,14122,14
I know it is a minor detail, but while we are at it, leave a space after the comma as in the rest of the records.

2022-08-31 17:31 UTC, seobryn approved these changes

2022-08-31 17:31 UTC, merged